name: easy_permissions_handler
description: Simplify permission requests and checks. Handle mandatory/optional permissions with custom dialogs if needed.
version: 1.0.0
homepage: https://github.com/georgesamirmansour/EasyPermission


environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

